# Generated by Django 3.2.6 on 2021-12-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donetask',
            name='date_ended',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
